### ISSUE TITLE
Guille - Project 1

### ISSUE THREAD

**Issue by Yoith** [Ironhack-data-bcn-january-2024/project-I-pandas#1]
https://github.com/Yoith/project-1

**Comment by breogann** [comment]
Hola Guille! 🙋🏻‍♂️

Te cuento:

_(si ves este comentario en github, el código aparecerá formateado)_

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: está perfecto. No has subido ningún archivo oculto/temporal a github, o sea que estupendo.
    - Tampoco has subido el csv original, como pedían los autores de kaggle
    - Las carpetas de data y de src están perfect.
    - No tienes ninguna carpeta de data. Está bien, pero, sólo hacía falta ignorar el datadset inicial. El archivo, una vez limpio y procesado, sí lo puedes exportar y de hecho te recomiendo que lo cojas como hábito.
- El **[README.md](http://readme.md/) ✍🏻**: el readme esta super bien. Has "ubicado" al lector en qué se va a encontrar y has dado un montón de contexto. 
    - Por la parte visual, ya que tienes los plots exportados, puedes aprovechar para incluirlos en el README. Sólo necesitas hacer como en jupyter notebook: `![nombre](ruta relativa a tu .png)`
    - Por completitud, puedes añadir si quieres más información sobre la estructura de los datos.
    - Incluye el enlace (público) a canvas en el README.md, o incluso una captura también. La presentación estuvo **genial** o sea que aprovechala. 
- La **modularización 📉**: no era necesario para este proyecto, pero lo pediremos para el siguiente. Es cuestión de meter en funciones y luego repartirlas en archivos de python dentro de la carpeta src para ir luego re-importándolas en los mismos notebooks. 

- El **código 👩‍💻:**
    - La limpieza y el story telling:
        - Los jupyter: Están bien guiados con los títulos y los comentarios 🔥.
        - En cuanto a esto: 
```python
count_activity = sharks["activity"].value_counts().head(30)
```
está genial porque justificas el por qué has decidido quedarte con los primeros 30. 
        - Has hecho función:
```python
def strip_columns(df):
    df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
    return df
``` 
que es sencilla y además te vale para más de un dataset. Aunque sea sencilla, el hábito de encapsular es necesario.
- Genial haber usado`pycountry`. No hay que reinventar la rueda y para eso están. 
- En las líneas de código donde utilizas el np.where (que por cierto, muy bien porque siempre se nos olvida ese método), puedes mejorarlo haciendco un diccionario para mapearlo, y entonces hacer una función. Es decir, `{"boat": ["boating", "boats", "boatomg"]} ` y así tienes una sola función parametrizada.

- Intenta no dejar errores en el código. Si lo quieres mantener, inclúyelo en unas triples comillas con un comentario (igualmente veo que has comentado el por qué te lo da 👏 )

- En cuanto a los plots: sencillos, con los ejes claros, muestran lo que tienen que mostrar y no hay ruido. Como mucho, ordenaría el de las actividades por el count. 
  

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
