### ISSUE TITLE
[Toni] - Sharks

### ISSUE THREAD

**Issue by ToniDaCosta** [Ironhack-data-bcn-january-2024/project-I-pandas#5]
https://github.com/ToniDaCosta/sharknado

**Comment by breogann** [comment]
Hola Toni! 🙋🏻‍♂️

Te cuento:

_(si ves este comentario en github, el código aparecerá formateado)_

- Respecto a la **organización del repositorio 📚**
    - Como pijería mía, si tienes un proceso secuencial que sigues en los notebooks, dirigiría la atención de quien lea tu repo numerando el nombre de los notebooks. 
    - No se te ha colado ningún archivo temporal, y veo de hecho que es porque los `.ipynb_checkpoints` los has ignorado, o sea que genial. El `.gitignore` no es sólo para las contraseñas ni tokens.
    - Tienes un par de notebooks que me aparecen como vacíos. SI no son problema mío (conexión) y es porque realmente están vacíos, déjalos fuera del repo. Todo aquello que genere ruido, intenta no incluirlo.
  

- El **[README.md](http://readme.md/) ✍🏻**: 
     - "This is a project to learn how to clean data using several methods." No hace falta que pongas que es un proyecto educativo, simplemente puedes ponerlo como: tengo estas preguntas y esta es mi solución. 
     - Has dado contexto sobre cómo recibes la información. Esto me parece clave y no muchos de vosotros lo acabáis haciendo y me parece crucial. Al final, si hablas de lo que has recibido y lo que has devuelto, dejas ver el valor que aportas. Muchas veces en data, al no tener más que visualizaciones, es difícil ver lo que aportáis porque queda invisible (el scrapping, el manejo de bases de datos, etc). 
     - Cuidado con typos: `raws ` en vez de `rows`. 
    - Ten en cuenta también que has reciclado las instrucciones del portal del estudiante. No funciona de cara a una perona que llegue de nuevas a tu repo.
    - Para incluir snippets de código en markdown, puedes hacer como en las celdas de notebook: 

<img width="215" alt="Screenshot 2024-02-09 at 23 02 14" src="https://github.com/Ironhack-data-bcn-january-2024/project-I-pandas/assets/54676992/674c52dc-ec5d-47c8-81d2-add7c2e448b2">
así pero reemplazando el json por python.
- Mencionas la sintaxis para generar los plots pero no los incluyes en el readme. Aprovecha que es precisamente la única parte visual que puedes utilziar (no como los desarrolladores web o los UX/UI, que sí tienen un producto a presentar). Los plots son tus amigos, explótalos para enseñar tus conclusiones.
- Incluye la presentación que hagas en el readme: puedes incluir el enlace a canva.
- En general, el readme debería cumplir la función de que la persona que lo lea entienda perfectamente el problema, los pasos y la solución. No debería tener las instrucciones para replicarlo paso a paso pero sí las herramientas. Es decir: en el readme el contexto sobre el proyecto y en el repositorio las herramientas para replicarlo (como el listado del ibrerías o el `requirements.txt` que alguna vez hemos hablado en clase)

- La **modularización 📉**: no era necesario para este proyecto, pero lo pediremos para el siguiente. Es cuestión de meter en funciones y luego repartirlas en archivos de python dentro de la carpeta src para ir luego re-importándolas en los mismos notebooks. 

- El **código 👩‍💻:**
     - Tienes varios errores ejecutados en los notebooks, intenta o bien comentar el código que genera el error o borrar la celda. Si simplemente tienes warnings, los puedes ignorar (sabiendo que quieres ignorarlos), utilizando:
```python
import warnings
warnings.filterwarnings('ignore')
```
- Lo mismo con el notebook de Visualization: está dpublicado, ¿no? veo que tienes lo mismo y está más completo en el de Sharknado.
- En cuanto a código, la verdad que no tengo mucho que decirte. Veo que has encontrado la forma de incluir los porcentajes en las barras, o sea que congrats por eso. Por lo demás, sólo te diría que la configuración de los plots la pongas jutno con los imports, siempre al principio. Al final ten en cuenta que afecta a todos los plots, por lo que si va al principio, te aseguras la consistencia en las imágenes. También, puedes meter el código en funciones. Estlo lo tienes que hacer sí o sí para el resto de lois proyectos.  
   
- En cuanto a los plots 📊: 
     -  Lo que te dije en la presentación: los ejes siempre tienen que ir ordenados si son barras, sea creciente o decreciente.
     - El de distribution of shark species, si no has podido procesar los valores de esa columna, no lo incluiría. La visualización tiene que simplificar la comprensión de los datos. Es el tradeoff entre simplicidad y pérdida de detalle. En ese caso, teniendo nombres de valores taaaaan largos, se anula el propósito. O bien los recategorizas, o descartaría ese plot.
     - El gráfico de líneas está súuuper bien. 
     - En el de ataques por sexo, veo que tienes cuatro categorías. Parece que te ha qudado alguna por limpiar!

Las únicas cosas a cambiar son aspectos formales que son detalles. Arreglarlos supone poco cote pero aportan mucho beneficio. Si cambias esto, te va a quedar un repo súper pulido y mucho más detallado. Vas bien Toni, ánimo con los siguientes 💪 💪 

![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
